apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: compredict-task
  name: fast
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: pd-ssd