version: '3.7'

services:
  django:
    build: . 
    volumes:
      - ./django_app/:/usr/local/django
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_ENGINE=postgresql_psycopg2
      - POSTGRES_DB=postgres-db
      - POSTGRES_USER=compredict
      - POSTGRES_PASSWORD=PenPineappleApplePen
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

